### ISSUE TITLE
problems about installation

### ISSUE THREAD

**Issue by 2018nanopore1** [usnistgov/mosaic#101]
Could you provide me some help?
Mosaic library(mosaic-nist) is not getting installed using anaconda prompt and not even on PyCharm. I tried upgrading every packages within mosaic which was issue earlier but after upgrading all packages also its giving some error. 

Also the scripts shown in the user guide document are giving error when I am running it using cloning the repository of mosaic-nist on Github. I am working on Python 2.7 as mosaic is not compatible on Python 3

**Comment by abalijepalli** [comment]
These are preliminary instructions on building MOSAIC from source on Windows. Note that the GUI appears to be broken under Windows when build from the Git repository. 

Install Anaconda for Python 2.7

Open Anaconda Prompt/Terminal (Start->Anaconda2->Anaconda Prompt)

Create the basic environment with most of the packages mosaic needs to run
- Type"conda create -n mosaicENV python=2.7 pandas=0.20.3 nose=1.3.7 numpy=1.11.1 scipy=0.18.1 docutils=0.14 flask=0.12.2 matplotlib=1.5.3 pyqt=4"
- Hit return to proceed with installation

Activate the new environment
- Type "conda activate mosaicENV"

Install some aditional packages. First we need to add the conda-forge channel
- Type "conda config --add channels conda-forge"
- Type "conda install lmfit=0.9.3 uncertainties=2.4.8.1 PyWavelets=0.5.2 coverage=4.5.1 codecov=2.0.15"
- Hit return to proceed with installation

Clone the mosaic repository
- See https://github.com/usnistgov/mosaic for instructions on cloning the repository.

Test the mosaic installation
- In the mosaic directory type "python setup.py test"
- Some tests may fails since the UI does not seem to work when installing from source. 

To run a script on Windows
- Open the python interepreter from the 'mosaic' directory.
- Type execfile('<path and name of script>'). As an example to run the analysis.py script in the bin directory, type 'execfile('bin\\analysis.py') from the top-lever mosaic folder.
