### ISSUE TITLE
CUSUM: Precision of residence times

### ISSUE THREAD

**Issue by abalijepalli** [usnistgov/mosaic#44]
CUSUM saves times (ResTime, StateResTime,, etc.) with limited precision. Running the query below returns only 2-3 digits of precision.

```javascript
select ProcessingStatus, BlockDepth, EventDelay, StateResTime, ResTime from metadata limit 2
```

```javascript
{
{"normal", {0.389212, 0.147366}, {0.4, 0.56, 0.586}, {0.16, 0.026}, 0.186},
{"normal", {0.0550025, 0.175752}, {0.4, 0.538,  0.688}, {0.138, 0.15}, 0.288}
}
```

Are the results being rounded within the code?

**Comment by shadowk29** [comment]
Because CUSUM detects jump locations as specific data points rather than fitting like the nonlinear fit case, the start and end times for events and subevents will always be a multiple of sampling frequency. I think that's all this is. If you increase the sampling frequency you will get better precision.

**Comment by abalijepalli** [comment]
That also seems to fit with the precision. The database I queried had a 2 us sampling frequency, so 3 decimal places.
